name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5

    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -f ./src/Dockerfile \
          -t marod12/primeira-pipeline:v${{ github.run_number }} \
          -t marod12/primeira-pipeline:latest \
          --push .

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps: 
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5

    - name: Configuração de contexto do Kubernetes
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}

    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          marod12/primeira-pipeline:v${{ github.run_number }}
